http://localhost:8080/api/v1/doctor

###


#add doctor
#admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInVzZXJJZCI6IjVmOWFiN2ExOTA5MDczMjU5YzZkNTM2MyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTYwNDA0NzE0MiwiZXhwIjoxNjA0NDA3MTQyfQ.-TcbCLbSUddJaV3Mk3oCRaQrKhRvG66WxSkoFyPzr4c

POST http://localhost:8080/api/v1/doctor/add
Content-Type: application/json

{
    "firstname": "doctor",
    "lastname": "doctor",
    "cellphone_num": "123456789",
    "email_add": "doctor@gmail.com"
}

###

#get all doctor
http://localhost:8080/api/v1/doctor/show

###

#get  doctor by lastname or firstanme
http://localhost:8080/api/v1/doctor/show/doctor
